#include "names.h"

/***************************************************
 * Names file: generation of all combo boxes names *
 ***************************************************/

//Thanks to kaspar01 from qhimm for making that list :I
QStringList CreateStageList(){
    QStringList btlscn;
    btlscn  << "000 - Balamb Garden Quad"
            << "001 - Dollet Bridge"
            << "002 - Dollet Trasmission Tower path"
            << "003 - Dollet Transmission Tower (Top)"
            << "004 - Dollet Transmission Tower (Elevator)"
            << "005 - Dollet Transmission Tower (Elevator 2 ?)"
            << "006 - Dollet City ? (Spice Spice Shop)"
            << "007 - Balamb Garden entrance gate"
            << "008 - Balamb Garden 1st Floor Hall"
            << "009 - Balamb Garden 2nd Floor Corridor"
            << "010 - Balamb Garden(Flyng Form) Quad"
            << "011 - Balamb Garden Outer Corridor"
            << "012 - Balamb Garden Training Center (elevator zone)"
            << "013 - Balamb Garden Norg's Floor"
            << "014 - Balamb Garden Underground Levels (Tube)"
            << "015 - Balamb Garden Underground levels (falling ladder zone?)"
            << "016 - Balamb Garden Underground levels (OilBoil Zone?)"
            << "017 - Timber Pub Area"
            << "018 - Timber Maniacs square"
            << "019 - Train (Deling Presidential Vagon)"
            << "020 - Deling City Sewers"
            << "021 - Deling City (Caraway Residence secret exit path?)"
            << "022 - Balamb Garden Class Room"
            << "023 - Galbadia Garden Corridor ?"
            << "024 - Galbadia Garden Corridor 2 ?"
            << "025 - Galbadia Missile Base"
            << "026 - Deep Sea Research Center (Entrance?)"
            << "027 - Balamb Town (Balamb Hotel road)"
            << "028 - Balamb Town (Balamb Hotel Hall)"
            << "029 - ? Diabolous Lair?"
            << "030 - Fire Cavern (path)"
            << "031 - Fire Cavern (Ifrit Lair)"
            << "032 - Galbadia Garden Hall"
            << "033 - Galbadia Garden Auditorium (Edea's battle?)"
            << "034 - Galbadia Garden Auditorium 2? (Edea's battle?)"
            << "035 - Galbadia Garden Corridor"
            << "036 - Galbadia Garden (Ice Hockey Field)"
            << "037 - ?? Some broken wall place..Ultimecia Castle?"
            << "038 - StarField?"
            << "039 - Desert Prison? (elevator?)"
            << "040 - Desert Prison? (Floor?)"
            << "041 - Esthar City (road)"
            << "042 - Desert Prison? (Top?)"
            << "043 - Esthar City (road2 ?)"
            << "044 - Missile Base? Hangar?"
            << "045 - Missile Base? Hangar2?"
            << "046 - Missile Base? Control room?"
            << "047 - Winhill Village main square"
            << "048 - Tomb of the Unknown King (Corridor)?"
            << "049 - Esthar City (road 3 ?)"
            << "050 - Tomb of the Unknown King (Boss Fight room)?"
            << "051 - Fisherman Horizon (Road)"
            << "052 - Fisherman Horizon (Train Station Square)"
            << "053 - Desert Prison? (Floor?)"
            << "054 - Salt Lake?"
            << "055 - Ultima Weapon Stage"
            << "056 - Salt Lake 2?"
            << "057 - Esthar Road"
            << "058 - Ultimecia's Castle (bridge)"
            << "059 - Esthar (square?)"
            << "060 - Esthar (?)"
            << "061 - Esthar (cave?)"
            << "062 - Esthar (cave2?)"
            << "063 - Esthar (Centra excavation site)"
            << "064 - Esthar (Centra excavation site)"
            << "065 - Esthar (Centra excavation site)"
            << "066 - Esthar (Centra excavation site)"
            << "067 - Lunatic Pandora?"
            << "068 - Lunatic Pandora"
            << "069 - Lunatic Pandora(Adel?)"
            << "070 - (Centra excavation site)"
            << "071 - (Centra excavation site)"
            << "072 - (Centra excavation site)"
            << "073 - (Centra excavation site)"
            << "074 - ? ?"
            << "075 - (Centra excavation site)"
            << "076 - Centra Ruins (Lower Level)"
            << "077 - Centra Ruins (Tower Level)"
            << "078 - Centra Ruins (Tower Level)"
            << "079 - Centra Ruins (Odin Room)"
            << "080 - Centra excavation site (Entrance)"
            << "081 - Trabia Canyon"
            << "082 - Ragnarok?"
            << "083 - Ragnarok?"
            << "084 - ? Diabolous Lair?"
            << "085 - Deep Sea Research Center (Entrance)"
            << "086 - Deep Sea Research Center"
            << "087 - Deep Sea Research Center"
            << "088 - Deep Sea Research Center"
            << "089 - Deep Sea Research Center"
            << "090 - Deep Sea Research Center"
            << "091 - Deep Sea Research Center"
            << "092 - ? ?"
            << "093 - ? Esthar shops?"
            << "094 - Tear's Point"
            << "095 - Esthar"
            << "096 - Ultimecia's Castle"
            << "097 - Ultimecia's Castle"
            << "098 - Ultimecia's Castle"
            << "099 - Ultimecia's Castle"
            << "100 - Deling City (Edea's Room)"
            << "101 - Balamb Plains?"
            << "102 - Desert Canyon?"
            << "103 - Desert?"
            << "104 - Snow-Covered Plains? (Trabia Region?)"
            << "105 - Wood"
            << "106 - Snow-Covered Wood"
            << "107 - Balamb Isle? (Beach zone?)"
            << "108 - ?Snow Beach?"
            << "109 - Esthar City"
            << "110 - Esthar City"
            << "111 - Generic Landscape? Dirt Ground"
            << "112 - Generic Landscape? Grass Ground"
            << "113 - Generic Landscape? Dirt Ground"
            << "114 - Generic Landscape? Snow Covered Mountains"
            << "115 - Esthar City"
            << "116 - Esthar City"
            << "117 - Generic Landscape?"
            << "118 - Esthar City"
            << "119 - Esthar City"
			<< "120 - Ultimecia's Castle"
			<< "121 - Ultimecia's Castle"
			<< "122 - Ultimecia's Castle"
			<< "123 - Ultimecia's Castle"
			<< "124 - Ultimecia's Castle"
			<< "125 - Ultimecia's Castle"
			<< "126 - Ultimecia's Castle"
			<< "127 - Ultimecia's Castle"
			<< "128 - Landscape"
			<< "129 - Landscape"
			<< "130 - Landscape"
			<< "131 - Landscape"
			<< "132 - Landscape"
			<< "133 - Landscape"
			<< "134 - Eshtar City"
			<< "135 - Landscape"
			<< "136 - Landscape (beach night)"
			<< "137 - Deling City (Edea's Room)"
			<< "138 - Ultimecia's Castle"
			<< "139 - Ultimecia's Castle (Tiamat)"
			<< "140 - Ultimecia's Castle"
			<< "141 - Ultimecia's Castle"
			<< "142 - Ultimecia's Castle"
			<< "143 - Eshtar City"
			<< "144 - Lunatic Pandora Lab"
			<< "145 - Lunatic Pandora Lab"
			<< "146 - Sorcerer memorial"
			<< "147 - Edea Dollet stage DISC 1 final battle"
			<< "148 - Tomb of the Unknown King [Boss Fight]"
			<< "149 - Prison control room"
			<< "150 - Landscape"
			<< "151 - Landscape"
			<< "152 - Balamb Garden (External Corridor)"
			<< "153 - Balamb Garden (External Corridor)"
			<< "154 - Balamb Garden (External Corridor)"
			<< "155 - Balamb Garden (External Corridor)"
			<< "156 - Balamb Garden (External Corridor)"
			<< "157 - Landscape"
			<< "158 - Landscape"
			<< "159 - Landscape"
			<< "160 - Debug Environment"
			<< "161 - Landscape"
			<< "162 - Landscape";
    return btlscn;
}

//KLITLIKA 2020 - 1st attempt to improve enemy list
QStringList CreateEnemyList(){
    QStringList enemynames;
    enemynames  << "000 - Dummy"
                << "001 - GIM52A"
                << "002 - Blobra"
                << "003 - Thrustaevis"
                << "004 - Geezard"
                << "005 - Belhelmel"
                << "006 - Glacial Eye"
                << "007 - SAM08G"
                << "008 - GIM47N"
                << "009 - Mesmerize"
                << "010 - Buel"
                << "011 - Sphinxaur"
                << "012 - Sphinxara"
                << "013 - Snow Lion"
                << "014 - Anacondaur"
                << "015 - Grat"
                << "016 - Cockatrice"
                << "017 - Caterchipillar"
                << "018 - Red Bat"
                << "019 - Blitz"
                << "020 - Fastitocalon"
                << "021 - Fastitocalon(Fake)"
                << "022 - Gesper"
                << "023 - Creeps"
                << "024 - Hexadragon"
                << "025 - Blood Soul"
                << "026 - Elastoi"
                << "027 - Armadodo"
                << "028 - Bite Bug"
                << "029 - Jelleye"
                << "030 - Tripoint (BOSS)"
                << "031 - Turtapod"
                << "032 - Wendigo"
                << "033 - Gayla"
                << "034 - Gerogero (BOSS)"
                << "035 - Death Claw"
                << "036 - Tri-Gace"
                << "037 - Grand Mantis"
                << "038 - Brysta"
                << "039 - Lefty"
                << "040 - Righty"
                << "041 - Blue Dragon"
                << "042 - Forbidden"
                << "043 - Bomb"
                << "044 - Abyss Worm"
                << "045 - Ochu"
                << "046 - Adamantoise"
                << "047 - Chimera"
                << "048 - Malboro"
                << "049 - Iron Giant"
                << "050 - Behemoth"
                << "051 - T-Rexaur"
                << "052 - Ruby Dragon"
                << "053 - Grendel"
                << "054 - Vysage"
                << "055 - Cactuar"
                << "056 - Tonberry"
                << "057 - Torama"
                << "058 - Funguar"
                << "059 - Imp"
                << "060 - PuPu (Optional BOSS)"
                << "061 - Ifrit (BOSS)"
                << "062 - Minotaur (Optional BOSS)"
                << "063 - Sacred (Optional BOSS)"
                << "064 - Base Leader (Red)
                << "065 - Cerberus (BOSS)"
                << "066 - Diablos (Optional BOSS)"
                << "067 - Bahamut (Optional BOSS)"
                << "068 - NORG Pod (BOSS)"
                << "069 - Garden Faculty (BOSS?)"
                << "070 - Odin (Optional BOSS)"
                << "071 - G-Soldier (Blue)"
                << "072 - Elite Soldier (Red)"
                << "073 - Wedge - Disc 1 (BOSS)"
                << "074 - Biggs - Disc 1 (BOSS)"
                << "075 - Fake President (BOSS)"
                << "076 - Guard (BLUE)"
                << "077 - NORG (BOSS)"
                << "078 - Esthar Soldier"
                << "079 - Esthar Soldier(Stronger)"
                << "080 - Right Orb (NORG BOSS)"
                << "081 - Left Orb (NORG BOSS)"
                << "082 - Gunblade (Seifer's Hyperion) (BOSS)"
                << "083 - Tonberry King (Optional BOSS)"
                << "084 - Jumbo Cactuar (Optional BOSS)"
                << "085 - Seifer (BOSS) (1st Fight) (Disc 1)"
                << "086 - Seifer (BOSS) (2nd Fight) (Disc 2)"
                << "087 - Seifer (BOSS) (3rd Fight) (Disc 2)"
                << "088 - Edea (1st Fight) (BOSS) (Disc 1)"
                << "089 - Propagator (Purple)"
                << "090 - Ultima Weapon (BOSS)"
                << "091 - Elvoret (BOSS)"
                << "092 - X-ATM092 (BOSS)"
                << "093 - Iguion (BOSS)"
                << "094 - Gargantua (BOSS)"
                << "095 - Granaldo (BOSS)"
                << "096 - Raldo (BOSS)"
                << "097 - Propagator (Dark Green)"
                << "098 - Propagator (Yellow)"
                << "099 - Oilboyle (mini-BOSS)"
                << "100 - Edea (2nd Fight) (Disc 2)"
                << "101 - BGH251F2 (1st Fight) (Missile Base)"
                << "102 - BGH251F2 (2nd Fight) (@ F.H. + DMGed)"
                << "103 - Abadon (BOSS)"
                << "104 - ?????? (BOSS)"
                << "105 - Mobile Type 8 (BOSS)"
                << "106 - Left Probe (BOSS)"
                << "107 - Right Probe (BOSS)"
                << "108 - Paratrooper (GREEN)"
                << "109 - Trauma (BOSS)"
                << "110 - Droma (BOSS)"
                << "111 - Propagator (Red)"
                << "112 - Adel (BOSS)"
                << "113 - *Rinoa (Attached to Adel)"
                << "114 - Omega Weapon (Optional SUPER-BOSS)"
                << "115 - Sorceress (1st)"
                << "116 - Sorceress (2nd)"
                << "117 - Sorceress (Wormlike)"
                << "118 - UFO? (Pupu's Flying Saucer) *Optional"
                << "119 - Fujin - Disc 2 (BOSS)"
                << "120 - Raijin - Disc 2 (BOSS)"
                << "121 - Ultimecia - 1st Form (BOSS)"
                << "122 - Griever - 2nd Form (BOSS)"
                << "123 - (Ulti's Griever MERGING - BALL?) (BOSS)"
                << "124 - Ulti-Griever fusion - 3rd Form (BOSS)"
                << "125 - Helix - Ulti's Minions (BOSS)"
                << "126 - Ultimecia - 4th Form (Final) (BOSS)"
                << "127 - Ultimecia - 4th Form Lower Body (No model) (BOSS)"
                << "128 - Seifer (BOSS) (4th Fight) (Disc 3)"
                << "129 - Slapper (ICE HOCKEY)"
                << "130 - Red Giant (BOSS)"
                << "131 - Elnoyle (BOSS)"
                << "132 - Tiamat (BOSS)"
                << "133 - Catoblepas (BOSS)"
                << "134 - Wedge - Disc 3 (BOSS)"
                << "135 - Biggs - Disc 3 (BOSS)"
                << "136 - Fujin - Disc 3 (BOSS)"
                << "137 - Rajin - Disc 3 (BOSS)"
                << "138 - UFO with Statue? *Optional "
                << "139 - UFO With Cow? *Optional "
                << "140 - UFO With Crop Circles? *Optional "
                << "141 - UFO With Pyramid? *Optional "
                << "142 - Gunblade (Seifer's Hyperion) (BOSS)"
                << "143 - Base Soldier (BLUE)";
                << "144 - DUMMY";
                << "145 - DUMMY";
                << "146 - DUMMY";
                << "147 - DUMMY";
                << "148 - DUMMY";
                << "149 - DUMMY";
                << "150 - DUMMY";
                << "151 - DUMMY";
                << "152 - DUMMY";
                << "153 - DUMMY";
                << "154 - DUMMY";
                << "155 - DUMMY";
                << "156 - DUMMY";
                << "157 - DUMMY";
                << "158 - DUMMY";
                << "159 - DUMMY";
                << "160 - DUMMY";
                << "161 - DUMMY";
                << "162 - DUMMY";
                << "163 - DUMMY";
                << "164 - DUMMY";
                << "165 - DUMMY";
                << "166 - DUMMY";
                << "167 - DUMMY";
                << "168 - DUMMY";
                << "169 - DUMMY";
                << "170 - DUMMY";
                << "171 - DUMMY";
                << "172 - DUMMY";
                << "173 - DUMMY";
                << "174 - DUMMY";
                << "175 - DUMMY";
                << "176 - DUMMY";
                << "177 - DUMMY";
                << "178 - DUMMY";
                << "179 - DUMMY";
                << "180 - DUMMY";
                << "181 - DUMMY";
                << "182 - DUMMY";
                << "183 - DUMMY";
                << "184 - DUMMY";
                << "185 - DUMMY";
                << "186 - DUMMY";
                << "187 - DUMMY";
                << "188 - DUMMY";
                << "189 - DUMMY";
                << "190 - DUMMY";
                << "191 - DUMMY";
                << "192 - DUMMY";
                << "193 - DUMMY";
                << "194 - DUMMY";
                << "195 - DUMMY";
                << "196 - DUMMY";
                << "197 - DUMMY";
                << "198 - DUMMY";
                << "199 - DUMMY";
        return enemynames;
}
